### ISSUE TITLE
CT: Failed validation for validators[0]: Should not be NaN

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#198] opened 2023-10-24 21:54 UTC
```
keplers-laws : fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1698182110331/keplers-laws/keplers-laws_en.html?continuousTest=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1698182110331%22%2C%22timestamp%22%3A1698182696330%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"typeName": "NumberIO",
"supertype": {
"typeName": "ObjectIO",
"documentation": "The root of the IO Type hierarchy",
"methods": {},
"events": [],
"metadataDefaults": {
"phetioTypeName": "ObjectIO",
"phetioDocumentation": "",
"phetioState": true,
"phetioReadOnly": false,
"phetioEventType": "MODEL",
"phetioHighFrequency": false,
"phetioPlayback": false,
"phetioDynamicElement": false,
"phetioIsArchetype": false,
"phetioFeatured": false,
"phetioDesigned": false,
"phetioArchetypePhetioID": null
},
"dataDefaults": {
"initialState": null
},
"methodOrder": [],
"parameterTypes": [],
"validator": {
"validationMessage": "Validation failed IOType Validator: ObjectIO"
},
"defaultDeserializationMethod": "fromStateObject",
"stateSchema": null,
"isFunctionType": false
},
"documentation": "IO Type for Javascript's number primitive type",
"methods": {},
"events": [],
"metadataDefaults": {},
"dataDefaults": {},
"methodOrder": [],
"parameterTypes": [],
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"defaultDeserializationMethod": "fromStateObject",
"stateSchema": {
"displayString": "number",
"validator": {},
"compositeSchema": null
},
"isFunctionType": false
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{
"validationMessage": "Number must be within rangeProperty value: [Range (min:-Infinity max:Infinity)]"
}
]
}
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1698182110331/assert/js/assert.js:28:13)
at assert (validate.ts:26:16)
at validate (ReadOnlyProperty.ts:296:14)
at _notifyListeners (ReadOnlyProperty.ts:262:13)
at unguardedSet (ReadOnlyProperty.ts:246:11)
at set (Property.ts:54:10)
at (EllipticalOrbitEngine.ts:238:32)
at updateBodyDistances (EllipticalOrbitEngine.ts:299:9)
at update (EllipticalOrbitEngine.ts:177:13)
at callback (Multilink.ts:111:10)
```

**Comment by AgustinVallejo** [comment] 2023-10-26 21:52
@pixelzoom Does the above issue, and the fact that it's closed now, mean this one could also be closed?

**Comment by pixelzoom** [comment] 2023-10-27 19:48
Indeed this seems to be resolved, no longer reported in CT, so closing.

**Comment by pixelzoom** [comment] 2023-12-16 15:39
Reopening.  Beginning 12/15/23 @ 5:34:53pm, this is failing on every CT cycle.

**Comment by AgustinVallejo** [comment] 2023-12-20 14:55
This potentially fixes the bug by first assuring the position is never (0,0) and making positionProperty reentrant. Let's wait to see if CT becomes green. Should be cherry picked before closing!

**Comment by AgustinVallejo** [comment] 2023-12-20 20:48
Nope, still happening

**Comment by AgustinVallejo** [comment] 2023-12-21 15:38
Found the cause, in `enforceValidVelocity()` within the EllipticalOrbitEngine, there's a check so that the velocity and position vectors are not aligned. However, if they are opposite, the sine function of their angle returns 1.2246467991473532e-16 which doesn't pass as 0. I'm checking with devs to see what is the preferred way to address this and it should solve it.

**Comment by AgustinVallejo** [comment] 2023-12-21 16:29
I have high confidence in the above fix. Let's wait to CT to confirm it

**Comment by AgustinVallejo** [comment] 2023-12-21 18:45
CT looking green! Closing this issue

**Closed by AgustinVallejo** 2023-12-21 18:45 UTC
Labels: type:bug, status:ready-to-cherry-pick, type:automated-testing
