### ISSUE TITLE
Suggestion for looking at orbital properties of target orbits

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/keplers-laws#251] opened 2024-02-05 21:38 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chorme
**Problem description**
For https://github.com/phetsims/qa/issues/1034
I noticed that the target orbits don't seem to exactly produce the periods of the planets in question. For instance, Mercury has a period of .27 yr instead of .24. I wanted to check the exact properties of the target orbit, semi major axis for example, to see if everything matched up. This feature does not seem to be available.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Kepler's Laws‬
URL: https://phet-dev.colorado.edu/html/keplers-laws/1.2.0-rc.1/phet/keplers-laws_all_phet.html
Version: 1.2.0-rc.1 2024-02-02 22:32:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language: en-US
Window: 1536x695
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by AgustinVallejo** [comment] 2024-02-06 23:10
The period not being the same wouldn't worry me, since what's most likely is that the user didn't get an exact reproduction of the target orbit, so period differences are to be expected. However, it'd be nice to show (at least in studio) the actual orbital parameters of the orbit you're trying to reproduce.

**Comment by pixelzoom** [comment] 2024-02-07 18:31
> However, it'd be nice to show (at least in studio) the actual orbital parameters of the orbit you're trying to reproduce.

Each target orbit is described in the TargetOrbit rich enumeration.  Studio displays enumeration values using their name ('MERCURY', 'EARTH', etc.) and there's not currently a way to display the other fields in a rich enumeration.  So I recommended to just put the info (`eccentricity`, `semiMajorAxis`) for each target orbit in examples.md.

**Comment by AgustinVallejo** [comment] 2024-02-07 18:31
Spoke with @pixelzoom and it seems there's no easy way to display that information in studio. In that case, I think it's useful to have in teacher-tips.md as well as in examples.md

**Comment by arouinfar** [comment] 2024-02-08 02:10
Looks great, thanks @AgustinVallejo!

**Comment by Nancy-Salpepi** [comment] 2024-02-16 13:26
target orbital info has been added to examples.md and model.md 

Closing!

**Closed by Nancy-Salpepi** 2024-02-16 13:26 UTC
Labels: type:bug, status:ready-to-cherry-pick
